version: '3.8'

services:
  web:
    build: .
    command: bash -c 'while !</dev/tcp/db/5433; do sleep 1; done; uvicorn main:app --host 0.0.0.0'
    volumes:
      - .:/code
    ports:
      - 8000:8000
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5433/workgenius
    depends_on:
      - db
  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5433:5433"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=workgenius
    command: -p 5433
volumes:
  postgres_data: